In [3]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a.size

3

In [8]:
a.itemsize

4

In [9]:
a.data

In [10]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print('Type: ',b.dtype)
print("num of dim: ",b.ndim)
print('shape: ',b.shape)
print('size: ',b.size)


Type:  int32
num of dim:  2
shape:  (3, 3)
size:  9


In [13]:
c=np.array([
    [
     [1,2],
     [3,4]
    ],
    [
     [5,6],
     [7,8]   
    ]
])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
print('Type: ',c.dtype)
print("num of dim: ",c.ndim)
print('shape: ',c.shape)
print('size: ',c.size)

Type:  int32
num of dim:  3
shape:  (2, 2, 2)
size:  8


In [4]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.random.random((2,2))

array([[0.27732874, 0.23045505],
       [0.87766304, 0.33993533]])

In [10]:
np.random.rand(3,4)

array([[0.43989786, 0.86467336, 0.86940293, 0.52924596],
       [0.03537506, 0.24665815, 0.55619672, 0.36341942],
       [0.9015068 , 0.98346987, 0.80750541, 0.4293845 ]])

In [11]:
np.random.randn(2,1)

array([[-0.08437274],
       [ 2.5497474 ]])

In [12]:
np.random.randint(4,9)

7

In [13]:
np.random.randint(5,size=(3,3))

array([[4, 1, 3],
       [3, 4, 0],
       [4, 2, 4]])

In [14]:
np.full((2,2),(1,2))

array([[1, 2],
       [1, 2]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.empty((2,3),dtype=int)

array([[  669015008,         539,           0],
       [          0,           1, -2147483648]])

In [2]:
x=np.arange(0,12)

In [3]:
x.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
x.reshape(2,4)

ValueError: cannot reshape array of size 12 into shape (2,4)

In [5]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
x.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
x.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
x.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
x=x.reshape(3,4)

In [14]:
x.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [15]:
a=np.arange(4)

In [16]:
a

array([0, 1, 2, 3])

In [17]:
b=np.arange(4,8)
b

array([4, 5, 6, 7])

In [18]:
a+b

array([ 4,  6,  8, 10])

In [19]:
np.add(a,b)

array([ 4,  6,  8, 10])

In [20]:
a-b

array([-4, -4, -4, -4])

In [22]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [23]:
a*b

array([ 0,  5, 12, 21])

In [24]:
np.multiply(a,b)

array([ 0,  5, 12, 21])

In [25]:
a/b

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [26]:
np.divide(a,b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [27]:
a=np.array([[4,5,6],
           [7,8,9]])
a

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [29]:
c=np.dot(a,b)
c

array([32, 50])

In [30]:
a=np.arange(4,13).reshape(3,3)

In [31]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a.dot(b)

array([[15., 15., 15.],
       [24., 24., 24.],
       [33., 33., 33.]])

In [36]:
b.dot(a)

array([[21., 24., 27.],
       [21., 24., 27.],
       [21., 24., 27.]])

In [37]:
a+=3

In [38]:
a

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [39]:
a-=2
a

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [40]:
a*=2
a

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [41]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [43]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [44]:
np.log(a)

<ipython-input-44-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [45]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [46]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [47]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [49]:
a.sum()

6

In [50]:
a.min()

0

In [51]:
a.max()

3

In [52]:
a.argmax()

3

In [53]:
a.mean()

1.5

In [54]:
a.std()

1.118033988749895

In [55]:
x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
y=np.zeros((4,4))

In [58]:
np.vstack((x,y))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.hstack((x,y))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [60]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

In [61]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
np.row_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
[b,c]=np.hsplit(a,2)

In [65]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [66]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [67]:
[b,c]=np.vsplit(a,2)

In [68]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
[x,y,z]=np.split(a,[1,3],axis=1)

In [71]:
x

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [72]:
y

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [73]:
z

array([[ 3],
       [ 7],
       [11],
       [15]])

In [74]:
[x,y,z]=np.split(a,[1,3],axis=0)

In [75]:
x

array([[0, 1, 2, 3]])

In [76]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
z

array([[12, 13, 14, 15]])