In [3]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a.size

3

In [8]:
a.itemsize

4

In [9]:
a.data

In [10]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print('Type: ',b.dtype)
print("num of dim: ",b.ndim)
print('shape: ',b.shape)
print('size: ',b.size)


Type:  int32
num of dim:  2
shape:  (3, 3)
size:  9


In [13]:
c=np.array([
    [
     [1,2],
     [3,4]
    ],
    [
     [5,6],
     [7,8]   
    ]
])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
print('Type: ',c.dtype)
print("num of dim: ",c.ndim)
print('shape: ',c.shape)
print('size: ',c.size)

Type:  int32
num of dim:  3
shape:  (2, 2, 2)
size:  8


In [4]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.random.random((2,2))

array([[0.27732874, 0.23045505],
       [0.87766304, 0.33993533]])

In [10]:
np.random.rand(3,4)

array([[0.43989786, 0.86467336, 0.86940293, 0.52924596],
       [0.03537506, 0.24665815, 0.55619672, 0.36341942],
       [0.9015068 , 0.98346987, 0.80750541, 0.4293845 ]])

In [11]:
np.random.randn(2,1)

array([[-0.08437274],
       [ 2.5497474 ]])

In [12]:
np.random.randint(4,9)

7

In [13]:
np.random.randint(5,size=(3,3))

array([[4, 1, 3],
       [3, 4, 0],
       [4, 2, 4]])

In [14]:
np.full((2,2),(1,2))

array([[1, 2],
       [1, 2]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.empty((2,3),dtype=int)

array([[  669015008,         539,           0],
       [          0,           1, -2147483648]])